# Generated by Django 6.0 on 2025-12-19 18:45

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_task_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=records.models.task_attachment_upload_path),
        ),
    ]
